### ISSUE TITLE
Icons from manifest are missing

### ISSUE THREAD

**Issue by pepelsbey** [notwaldorf/notwaldorf.github.com#8]
Is seems `images/icon-*.png` never existed in [manifest.json](https://github.com/notwaldorf/notwaldorf.github.com/blob/master/manifest.json).

**Comment by notwaldorf** [comment]
Ohhh yeah. I think when I tried to add a SW to this it ended up being a giant disaster, so i've left it in a half baked state. Thanks for the reminder!

**Comment by notwaldorf** [comment]
Four years later but I think I fixed it? 🎉
